{
  "api": {
    "type": "openapi",
    "url": "https://openai-collections.chat-plugin.lobehub.com/weather-gpt/openapi.json",
    "has_user_authentication": false
  },
  "auth": {
    "type": "none"
  },
  "contact_email": "stey@vercel.com",
  "description_for_human": "Get current weather information for a specific location.",
  "description_for_model": "Use the WeatherGPT plugin to automatically fetch current weather information for a specific location when it's being generated by the ChatGPT assistant. The plugin will return weather data, including temperature, wind speed, humidity, and other relevant information, as well as a link to a page that has all the information. Links will always be returned and should be shown to the user. The weather data can be used to provide users with up-to-date and accurate weather information for their desired location.",
  "legal_info_url": "https://weathergpt.vercel.app/legal",
  "logo_url": "https://openai-collections.chat-plugin.lobehub.com/weather-gpt/logo.webp",
  "name_for_human": "WeatherGPT",
  "name_for_model": "WeatherGPT",
  "schema_version": "v1"
}
